apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-backend
  namespace: kafka-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-backend
  template:
    metadata:
      labels:
        app: stats-backend
    spec:
      containers:
      - name: stats-backend
        image: ondrejnr1/stats-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stats-backend
  namespace: kafka-web
spec:
  selector:
    app: stats-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
